travis:
  secure:
    BINSTAR_TOKEN: gS6hG+KOqSxvUov6tmBU2jtu9qwJ1ME/8DnwrOhLpcFkl/2nDy87l9rl1K4Jr42zGcnPJDD+pcMqaSOeV68KomoxpHiDVkxZc7luChVmrvKJ8SmBMosXBuWjdDJ0LXZuQ5+8j2YNh+D1R9uNLNauRm/m1D8aAJdyA4mvtiwifhMomesFYtFBp911JttH0irYLgNNa3o5sa0tzBygr9ZN6beu4FIKg0I4CyRo8z10tyti0tGz//21n3uvZM0XZ+tM5WmiOc9l2xMQi94NxvPeOslnyPWvDH7WXyyewOqr8vMtcrXOZHmM15b0CE6KEQrrT1kP59A/BBzS8I54ZwWwHFO04v8G9YTiL5TreSIYDeOmRFvoBiR0SyCMhlcGTl/7ZVCVg7Fpbq4+aGlGG7y3XIbuRu5XpHEWjAgLhgC9W1/+YN4pL5hQeoVdrMNUrxjah+UnHdTEUuaMmwVPCFiDLRpzw2+VYZpGuva5F2EvvJi29UqD2HW7UNd1NWIL4OyQDv2rwHbwpsYZBQNSYfQ+uttGL+p5jRWy4cvHrq4SHbBPhbzeWV+aU+KZBXZMDyMum+Hp7QF1K0ZS6q3gBLs/fArurQlIGKTgYPAX1QrXaCHE7S3ueXomkxkdgm6bgCNWhiXbdERoaT0qSAsVKHq1HZIT++B0QoATssMHajTY4q0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
